# SwiftLint 配置

included:
  - Sources
  - Tests

excluded:
  - Sources/Web
  - References
  - .build
  - build
  - DerivedData

# 启用的规则
opt_in_rules:
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - last_where
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

# 禁用的规则
disabled_rules:
  - trailing_comma
  - todo
  - opening_brace
  - nesting
  - force_cast
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - for_where
  - multiple_closures_with_trailing_closure

# 规则配置
line_length:
  warning: 150
  error: 700
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 1200
  error: 5000

type_body_length:
  warning: 800
  error: 3000

function_body_length:
  warning: 100
  error: 350

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - k
    - db
    - ok
    - to
    - vc
    - r
    - g
    - b
    - a
    - w
    - h
    - p
    - t
    - v
    - S

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 20
  error: 50

reporter: xcode
