name: MiNoteMac
options:
  bundleIdPrefix: com.minote
  deploymentTarget:
    macOS: "26.0"
  developmentLanguage: zh-Hans
  xcodeVersion: "15.0"
  
targets:
  MiNoteLibrary:
    type: framework
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - path: Sources/MiNoteLibrary
        excludes:
          - "**/*.md"
    resources:
      - path: Sources/MiNoteLibrary/Web
        type: folder
    settings:
      base:
        PRODUCT_NAME: MiNoteLibrary
        PRODUCT_BUNDLE_IDENTIFIER: com.minote.MiNoteLibrary
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        SWIFT_VERSION: "6.0"
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
  
  MiNoteMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    dependencies:
      - target: MiNoteLibrary
    sources:
      - path: Sources/MiNoteMac
        excludes:
          - "App.swift.backup"
    resources:
      - path: Sources/MiNoteMac/Resources
    settings:
      base:
        PRODUCT_NAME: MiNoteMac
        PRODUCT_BUNDLE_IDENTIFIER: com.minote.MiNoteMac
        MACOSX_DEPLOYMENT_TARGET: "26.0"
        SWIFT_VERSION: "6.0"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          ENABLE_DEBUG_DYLIB: YES
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    info:
      path: Info.plist
      properties:
        CFBundleName: "备忘录"
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        LSMinimumSystemVersion: "14.0"
        NSHumanReadableCopyright: "Copyright © 2024"
        NSPrincipalClass: AppDelegate
        NSHighResolutionCapable: true
        NSAccentColorName: Yellow

schemes:
  MiNoteMac:
    build:
      targets:
        MiNoteMac: all
    run:
      config: Debug
    test:
      config: Debug
