name: MiNoteMac
options:
  bundleIdPrefix: com.minote
  deploymentTarget:
    macOS: "15.0"
  developmentLanguage: zh-Hans
  xcodeVersion: "15.0"

targets:
  MiNoteLibrary:
    type: framework
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
        excludes:
          - "**/*.md"
          - "App/**"
    settings:
      base:
        PRODUCT_NAME: MiNoteLibrary
        PRODUCT_BUNDLE_IDENTIFIER: com.minote.MiNoteLibrary
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: "6.0"
        DEFINES_MODULE: YES
        GENERATE_INFOPLIST_FILE: YES
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        SKIP_INSTALL: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O

  MiNoteMac:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    dependencies:
      - target: MiNoteLibrary
        embed: true
    sources:
      - path: Sources/App
        excludes:
          - "App.swift.backup"
    resources:
      - path: Sources/App/Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: MiNoteMac
        PRODUCT_BUNDLE_IDENTIFIER: com.minote.MiNoteMac
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: "6.0"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        MARKETING_VERSION: "debug"
        CURRENT_PROJECT_VERSION: "0"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          ENABLE_DEBUG_DYLIB: YES
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    info:
      path: Info.plist
      properties:
        CFBundleName: "小米笔记"
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSMinimumSystemVersion: "15.0"
        NSHumanReadableCopyright: "Copyright © 2025"
        NSPrincipalClass: AppDelegate
        NSHighResolutionCapable: true
        NSAccentColorName: Yellow
        NSMicrophoneUsageDescription: "小米笔记需要访问麦克风以录制语音笔记"

  MiNoteLibraryTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "15.0"
    dependencies:
      - target: MiNoteLibrary
    sources:
      - path: Tests/NativeEditorTests
      - path: Tests/ViewModelTests
      - path: Tests/CoordinatorTests
      - path: Tests/CommandTests
      - path: Tests/ImportTests
      - path: Tests/SyncTests
      - path: Tests/Mocks
      - path: Tests/TestSupport
    settings:
      base:
        PRODUCT_NAME: MiNoteLibraryTests
        PRODUCT_BUNDLE_IDENTIFIER: com.minote.MiNoteLibraryTests
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O

schemes:
  MiNoteMac:
    build:
      targets:
        MiNoteMac: all
    test:
      targets:
        - MiNoteLibraryTests
  
  MiNoteLibrary:
    build:
      targets:
        MiNoteLibrary: all
    test:
      targets:
        - MiNoteLibraryTests
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - MiNoteLibraryTests
