name: MiNoteMac
options:
  bundleIdPrefix: com.minote
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: zh-Hans
  xcodeVersion: "15.0"
  
packages:
  # 如果有外部依赖，在这里添加

targets:
  MiNoteMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/MiNoteMac
    settings:
      base:
        PRODUCT_NAME: MiNoteMac
        PRODUCT_BUNDLE_IDENTIFIER: com.minote.MiNoteMac
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        ENABLE_DEBUG_DYLIB: YES  # 启用预览功能
      configs:
        Debug:
          ENABLE_DEBUG_DYLIB: YES
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        Release:
          ENABLE_DEBUG_DYLIB: NO
          SWIFT_OPTIMIZATION_LEVEL: -O
    info:
      path: Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: 1
        CFBundleShortVersionString: 1.0.0
        LSMinimumSystemVersion: 14.0
        NSHumanReadableCopyright: "Copyright © 2024"
        NSPrincipalClass: NSApplication
        NSMainStoryboardFile: ""
        NSHighResolutionCapable: true

schemes:
  MiNoteMac:
    build:
      targets:
        MiNoteMac: all
    run:
      config: Debug
    test:
      config: Debug

